# version: '2'
# services:
#     image: nginx
#     app:
#     volumes:
#           - .:/usr/share/nginx/html/
#     expose:
#          - "80"

version: '2'
services:
    app:
     image: nginx:1.9
     volumes:
     - .:/usr/share/nginx/html/
     expose:
     - "80"